export const BYOK_OPENROUTER_HEADER = 'x-openrouter-api-key'
export const BYOK_OPENROUTER_ENV_VAR = 'CODEBUFF_BYOK_OPENROUTER'
export const BYOK_OPENROUTER_BASE_URL_ENV_VAR =
  'CODEBUFF_BYOK_OPENROUTER_BASE_URL'
